export const isVip = true;
export const userInfo = {
    user: {
        avatar_url: 'https://f12stag.kkmh.com/default_avatar_image.jpg-w180',
        avatar_url_jpg: 'https://f12stag.kkmh.com/default_avatar_image.jpg-w180',
        grade: 0,
        head_charm_id: 0,
        head_charm_url: '',
        id: 3293487,
        nameplate_image: '',
        nickname: '18911',
        pub_feed: 0,
        reg_type: 'phone',
        reward_extra: { reward_title_color: '', reward_bg_color: '' },
        reward_honour_title: '',
        userTagList: [],
        user_role: 0,
        vip_icon: 'https://f12stag.kkmh.com/image/220322/r2XYGkIOO.png',
        vip_type: 1,
    },
};
export const vipInfo = {
    activity_vip: false,
    auto_keep: false,
    button_text: '续费',
    charge_page_extra_text: '，购买后有效期将顺延',
    has_charge_record: true,
    last_charge_source: '',
    last_charge_vip_days: 183,
    mine_page_expire_info: '',
    nameplate_id: 0,
    nameplate_image: '',
    red_point: false,
    remained_days: 165,
    remained_time: 14171360828,
    temporary_vip: false,
    vip_big_icon: 'https://f12stag.kkmh.com/image/220322/r2XYGkIOO.png',
    vip_expire_type: '',
    vip_expired_at: 1703847990584,
    vip_group_type: 14,
    vip_group_type_name: '非7天内充值会员',
    vip_info: ['2023.12.29到期'],
    vip_status: 0,
    vip_type: 3,
};
export const activeItemData = {
    id: 84,
    good_type: 2,
    iap_good_id: 'MEMBER_S_84',
    title: 'aj-test-h5',
    recharge_value: 333,
    mark_price: 22200,
    real_price: 22200,
    status: 1,
    sequence: 1,
    recharge_type: 5,
    recharge_type_name: 'H5支付',
    platform: 3,
    show_type: 1,
    renew_type: 1,
    version_code: 0,
    max_version_code: 0,
    wechat_plan_id: '',
    qq_plan_id: '',
    up_renew_id: 0,
    renew_title: '',
    description: '444',
    label_title: '111',
    show_recharge_value: 23230,
    show_recharge_period: 1,
    combo: 2,
    extra_info: '',
    edit_status: 0,
    selected: 0,
    sale_tips: '',
    sale_text: '',
    visitor_text: '',
    icon: '',
    banner: '',
    activity_status: 1,
    coupon: {
        usable_list: [],
        unreachable_list: [],
    },
    coupon_string: '{"usable_list":[],"unreachable_list":[]}',
    coupon_tips: '',
    discount_tips: '',
    promotion_btn_text: '',
    promotion_price: 22200,
    promotion_type: 0,
    promotion_text: '',
    taste_days: 0,
    usableCouponFirst: null,
    markPruice: 222,
    realPrice: 222,
};
export const membersList = [
    {
        id: 84,
        good_type: 2,
        iap_good_id: 'MEMBER_S_84',
        title: 'aj-test-h5',
        recharge_value: 333,
        mark_price: 22200,
        real_price: 22200,
        status: 1,
        sequence: 1,
        recharge_type: 5,
        recharge_type_name: 'H5支付',
        platform: 3,
        show_type: 1,
        renew_type: 1,
        version_code: 0,
        max_version_code: 0,
        wechat_plan_id: '',
        qq_plan_id: '',
        up_renew_id: 0,
        renew_title: '',
        description: '444',
        label_title: '111',
        show_recharge_value: 23230,
        show_recharge_period: 1,
        combo: 2,
        extra_info: '',
        edit_status: 0,
        selected: 0,
        sale_tips: '',
        sale_text: '',
        visitor_text: '',
        icon: '',
        banner: '',
        activity_status: 1,
        coupon: {
            usable_list: [],
            unreachable_list: [],
        },
        coupon_string: '{"usable_list":[],"unreachable_list":[]}',
        coupon_tips: '',
        discount_tips: '',
        promotion_btn_text: '',
        promotion_price: 22200,
        promotion_type: 0,
        promotion_text: '',
        taste_days: 0,
        usableCouponFirst: null,
        markPruice: 222,
        realPrice: 222,
    },
    {
        id: 76,
        good_type: 2,
        iap_good_id: 'MEMBER_S_76',
        title: '连续包月',
        recharge_value: 1,
        mark_price: 1500,
        real_price: 40,
        status: 1,
        sequence: 2,
        recharge_type: 5,
        recharge_type_name: 'H5支付',
        platform: 3,
        show_type: 1,
        renew_type: 2,
        version_code: 0,
        max_version_code: 0,
        wechat_plan_id: '120279',
        qq_plan_id: 'P_QQ_H5_MEMBER_DEFINED_CONTRACT',
        up_renew_id: 78,
        renew_title: '自动续费月高版本',
        description: '0.08/月',
        label_title: '连续包月会员',
        show_recharge_value: 1,
        show_recharge_period: 3,
        combo: 1,
        extra_info: '',
        edit_status: 0,
        selected: 0,
        sale_tips: '限时优惠',
        sale_text: '送1000KK币',
        visitor_text: '',
        icon: 'https://f12stag.kkmh.com/image/230606/eVghmUyI5.png',
        banner: 'https://f12stag.kkmh.com/image/230606/skMxYbfm3.png',
        activity_status: 1,
        coupon: {
            usable_list: [],
            unreachable_list: [],
        },
        coupon_string: '{"usable_list":[],"unreachable_list":[]}',
        coupon_tips: '',
        discount_tips: '低至0折',
        promotion_btn_text: '',
        promotion_price: 40,
        promotion_type: 0,
        promotion_text: '到期前1天自动续费0元/月,可随时取消',
        taste_days: 0,
        usableCouponFirst: null,
        markPruice: 15,
        realPrice: 0.4,
    },
    {
        id: 78,
        good_type: 2,
        iap_good_id: 'MEMBER_S_78',
        title: '1个月',
        recharge_value: 31,
        mark_price: 1800,
        real_price: 1,
        status: 1,
        sequence: 3,
        recharge_type: 5,
        recharge_type_name: 'H5支付',
        platform: 3,
        show_type: 1,
        renew_type: 1,
        version_code: 0,
        max_version_code: 0,
        wechat_plan_id: '',
        qq_plan_id: '',
        up_renew_id: 0,
        renew_title: '',
        description: '0.01/月高版本充值商品',
        label_title: '1个月会员',
        show_recharge_value: 1,
        show_recharge_period: 3,
        combo: 2,
        extra_info: '',
        edit_status: 0,
        selected: 0,
        sale_tips: '限时优惠',
        sale_text: '送500KK 币，每周累计领440KK 币（有效期2个月）',
        visitor_text: '',
        icon: 'https://f12stag.kkmh.com/image/230606/mCPbKLjIz.png',
        banner: 'https://f12stag.kkmh.com/image/230606/YzxPASAbt.png',
        activity_status: 1,
        coupon: {
            usable_list: [],
            unreachable_list: [],
        },
        coupon_string: '{"usable_list":[],"unreachable_list":[]}',
        coupon_tips: '',
        discount_tips: '低至0折',
        promotion_btn_text: '',
        promotion_price: 1,
        promotion_type: 0,
        promotion_text: '',
        taste_days: 0,
        usableCouponFirst: null,
        markPruice: 18,
        realPrice: 0.01,
    },
    {
        id: 103,
        good_type: 2,
        iap_good_id: 'MEMBER_S_103',
        title: '3个月',
        recharge_value: 93,
        mark_price: 5000,
        real_price: 30,
        status: 1,
        sequence: 4,
        recharge_type: 5,
        recharge_type_name: 'H5支付',
        platform: 3,
        show_type: 1,
        renew_type: 1,
        version_code: 0,
        max_version_code: 0,
        wechat_plan_id: '',
        qq_plan_id: '',
        up_renew_id: 0,
        renew_title: '',
        description: '3个月',
        label_title: '3个月会员',
        show_recharge_value: 3,
        show_recharge_period: 3,
        combo: 3,
        extra_info: '',
        edit_status: 0,
        selected: 0,
        sale_tips: '限时优惠',
        sale_text: '送1600KK 币，每周累计领440KK 币（有效期2个月）',
        visitor_text: '',
        icon: 'https://f12stag.kkmh.com/image/230606/mjs7p6nlH.png',
        banner: 'https://f12stag.kkmh.com/image/230606/0ne6TPGsC.png',
        activity_status: 1,
        coupon: {
            usable_list: [],
            unreachable_list: [],
        },
        coupon_string: '{"usable_list":[],"unreachable_list":[]}',
        coupon_tips: '',
        discount_tips: '',
        promotion_btn_text: '',
        promotion_price: 30,
        promotion_type: 0,
        promotion_text: '',
        taste_days: 0,
        usableCouponFirst: null,
        markPruice: 50,
        realPrice: 0.3,
    },
    {
        id: 89,
        good_type: 2,
        iap_good_id: 'MEMBER_S_89',
        title: '12个月',
        recharge_value: 372,
        mark_price: 32800,
        real_price: 1000,
        status: 1,
        sequence: 5,
        recharge_type: 5,
        recharge_type_name: 'H5支付',
        platform: 3,
        show_type: 1,
        renew_type: 1,
        version_code: 0,
        max_version_code: 0,
        wechat_plan_id: '',
        qq_plan_id: '',
        up_renew_id: 0,
        renew_title: '',
        description: '年费',
        label_title: '12个月会员',
        show_recharge_value: 1,
        show_recharge_period: 5,
        combo: 4,
        extra_info: '',
        edit_status: 0,
        selected: 0,
        sale_tips: '限时优惠',
        sale_text: '送7000KK 币，每周累计领440KK 币（有效期2个月）',
        visitor_text: '',
        icon: 'https://f12stag.kkmh.com/image/230606/Pg3dWIA8x.png',
        banner: 'https://f12stag.kkmh.com/image/230606/fOSzbcQiN.png',
        activity_status: 1,
        coupon: {
            usable_list: [],
            unreachable_list: [],
        },
        coupon_string: '{"usable_list":[],"unreachable_list":[]}',
        coupon_tips: '',
        discount_tips: '折合0元/月',
        promotion_btn_text: '',
        promotion_price: 1000,
        promotion_type: 0,
        promotion_text: '',
        taste_days: 0,
        usableCouponFirst: null,
        markPruice: 328,
        realPrice: 10,
    },
    {
        id: 77,
        good_type: 2,
        iap_good_id: 'MEMBER_S_77',
        title: '1个月会员_77',
        recharge_value: 1,
        mark_price: 1,
        real_price: 1,
        status: 1,
        sequence: 6,
        recharge_type: 5,
        recharge_type_name: 'H5支付',
        platform: 3,
        show_type: 1,
        renew_type: 1,
        version_code: 1111,
        max_version_code: 0,
        wechat_plan_id: '',
        qq_plan_id: '',
        up_renew_id: 0,
        renew_title: '',
        description: '1',
        label_title: 'aj-test-h5',
        show_recharge_value: 1,
        show_recharge_period: 3,
        combo: 2,
        extra_info: '',
        edit_status: 0,
        selected: 0,
        sale_tips: '',
        sale_text: '',
        visitor_text: '',
        icon: 'https://f12stag.kkmh.com/image/230606/Rl9R9tTaC.png',
        banner: 'https://f12stag.kkmh.com/image/230606/W3JtDaGWS.png',
        activity_status: 1,
        coupon: {
            usable_list: [],
            unreachable_list: [],
        },
        coupon_string: '{"usable_list":[],"unreachable_list":[]}',
        coupon_tips: '',
        discount_tips: '',
        promotion_btn_text: '',
        promotion_price: 1,
        promotion_type: 0,
        promotion_text: '',
        taste_days: 0,
        usableCouponFirst: null,
        markPruice: 0.01,
        realPrice: 0.01,
    },
];
export const topicDataList = [
    {
        id: 2122,
        title: '小程序/M站测试',
        title_icon: '',
        show_type: 4,
        banner_children: [
            {
                id: 4329,
                title: '王维测试2',
                cover_image: 'https://f12stag.kkmh.com/image/220602/8iMHUfv5P.webp-w320.w',
                icon_image: 'https://f12stag.kkmh.com/image/230530/O0KWsSaI7.png',
                icon_text: '',
                lower_detail: {
                    lower_type: 0,
                    description: '',
                    start_at: 0,
                    end_at: 0,
                    time: '',
                },
                action_target: {
                    action_type: 2,
                    target_id: 4329,
                    target_app_url: '',
                    target_web_url: '',
                    target_package_name: '',
                    target_title: '',
                    hybrid_url: '',
                    target_guide: 'none',
                    target_guide_name: '',
                    non_iap_supported: 0,
                    target_string: '',
                    target_type: 0,
                    activity_id: '',
                    parent_target_id: 0,
                    type: 2,
                },
                button_target: {
                    button_status: 0,
                },
                activity_info: {},
                behavior_view: {
                    behavior_type: 0,
                    behavior_param_view: {
                        topic_id: 4329,
                    },
                },
                status: 0,
                uuid: 'lk9gait5_4329_0.sc2fly28uus',
                description: '',
                extra_title_view: {},
            },
            {
                id: 1231,
                title: '三国演义动漫',
                cover_image: 'https://f12stag.kkmh.com/image/170717/ek4wo09jl.webp-w320.w',
                icon_image: 'https://f12stag.kkmh.com/image/230530/O0KWsSaI7.png',
                icon_text: '',
                lower_detail: {
                    lower_type: 0,
                    description: '',
                    start_at: 0,
                    end_at: 0,
                    time: '',
                },
                action_target: {
                    action_type: 2,
                    target_id: 1231,
                    target_app_url: '',
                    target_web_url: '',
                    target_package_name: '',
                    target_title: '',
                    hybrid_url: '',
                    target_guide: 'none',
                    target_guide_name: '',
                    non_iap_supported: 0,
                    target_string: '',
                    target_type: 0,
                    activity_id: '',
                    parent_target_id: 0,
                    type: 2,
                },
                button_target: {
                    button_status: 0,
                },
                activity_info: {},
                behavior_view: {
                    behavior_type: 0,
                    behavior_param_view: {
                        topic_id: 1231,
                    },
                },
                status: 0,
                uuid: 'lk9gait5_1231_0.uvfk97664oj',
                description: '',
                extra_title_view: {},
            },
            {
                id: 1886,
                title: '测试测试测试...',
                cover_image: 'https://f12stag.kkmh.com/image/180724/FL0380W61.webp-w320.w',
                icon_image: '',
                icon_text: '',
                lower_detail: {
                    lower_type: 0,
                    description: '',
                    start_at: 0,
                    end_at: 0,
                    time: '',
                },
                action_target: {
                    action_type: 2,
                    target_id: 1886,
                    target_app_url: '',
                    target_web_url: '',
                    target_package_name: '',
                    target_title: '',
                    hybrid_url: '',
                    target_guide: 'none',
                    target_guide_name: '',
                    non_iap_supported: 0,
                    target_string: '',
                    target_type: 0,
                    activity_id: '',
                    parent_target_id: 0,
                    type: 2,
                },
                button_target: {
                    button_status: 0,
                },
                activity_info: {},
                behavior_view: {
                    behavior_type: 0,
                    behavior_param_view: {
                        topic_id: 1886,
                    },
                },
                status: 0,
                uuid: 'lk9gait5_1886_0.vhae4c6nrof',
                description: '',
                extra_title_view: {},
            },
            {
                id: 143,
                title: '王爷不好混测...',
                cover_image: 'https://f12stag.kkmh.com/image/190510/knAqdaQyo.webp-w320.w',
                icon_image: '',
                icon_text: '',
                lower_detail: {
                    lower_type: 0,
                    description: 'VIP省480KK币',
                    start_at: 0,
                    end_at: 0,
                    time: '',
                },
                action_target: {
                    action_type: 2,
                    target_id: 143,
                    target_app_url: '',
                    target_web_url: '',
                    target_package_name: '',
                    target_title: '',
                    hybrid_url: '',
                    target_guide: 'none',
                    target_guide_name: '',
                    non_iap_supported: 0,
                    target_string: '',
                    target_type: 0,
                    activity_id: '',
                    parent_target_id: 0,
                    type: 2,
                },
                button_target: {
                    button_status: 0,
                },
                activity_info: {},
                behavior_view: {
                    behavior_type: 0,
                    behavior_param_view: {
                        topic_id: 143,
                    },
                },
                status: 0,
                uuid: 'lk9gait5_143_0.1s7q9rugiaf',
                description: '',
                extra_title_view: {},
            },
        ],
        vip_free_items: [],
        item_width: 810,
        item_height: 1074,
        action_target: {
            action_type: 13,
            target_id: 0,
            target_app_url: '',
            target_web_url: '',
            target_package_name: '',
            target_title: '',
            hybrid_url: '',
            target_guide: 'none',
            target_guide_name: '',
            non_iap_supported: 0,
            target_string: '',
            target_type: 0,
            activity_id: '',
            parent_target_id: 0,
            type: 13,
        },
        top_action_target: {
            action_type: 51,
            target_id: 2122,
            target_app_url: '',
            target_web_url: '',
            target_package_name: '',
            target_title: '小程序/M站测试',
            hybrid_url: '',
            target_guide: 'button',
            target_guide_name: '查看更多',
            non_iap_supported: 0,
            target_string: '',
            target_type: 0,
            activity_id: '',
            parent_target_id: 0,
            type: 51,
        },
        top_text_type: 0,
        count_down_millis: 0,
        activity_info: {},
        banner_type: 6,
        banner_type_name: '横滑',
        show_bottom_button: 0,
        member_target: {
            good_id: 0,
            real_price: 0,
            mark_price: 0,
            coupon_record_id: '',
            combo: 0,
        },
        module_type: 0,
        module_show_type: 0,
        uuid: 'lk9gait5_2122_0.59sezaxv7di',
        max: true,
    },
];
